"""Initial schema

Revision ID: d57368641f9a
Revises: None
Create Date: 2026-05-30 22:21:37.999211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57368641f9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_statuses',
    sa.Column('statusId', sa.Integer(), nullable=False),
    sa.Column('statusName', sa.String(length=50), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.PrimaryKeyConstraint('statusId')
    )
    op.create_index(op.f('ix_document_statuses_statusId'), 'document_statuses', ['statusId'], unique=False)
    op.create_index(op.f('ix_document_statuses_statusName'), 'document_statuses', ['statusName'], unique=True)
    op.create_table('roles',
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('roleName', sa.String(length=100), nullable=False),
    sa.Column('dashboardUrl', sa.String(length=255), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.PrimaryKeyConstraint('roleId')
    )
    op.create_index(op.f('ix_roles_roleId'), 'roles', ['roleId'], unique=False)
    op.create_index(op.f('ix_roles_roleName'), 'roles', ['roleName'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('planId', sa.Integer(), nullable=False),
    sa.Column('planName', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('limitConversions', sa.Integer(), nullable=True),
    sa.Column('limitAiUsage', sa.Integer(), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.PrimaryKeyConstraint('planId')
    )
    op.create_index(op.f('ix_subscription_plans_planId'), 'subscription_plans', ['planId'], unique=False)
    op.create_index(op.f('ix_subscription_plans_planName'), 'subscription_plans', ['planName'], unique=True)
    op.create_table('workspaces',
    sa.Column('workspaceId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.PrimaryKeyConstraint('workspaceId')
    )
    op.create_index(op.f('ix_workspaces_workspaceId'), 'workspaces', ['workspaceId'], unique=False)
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('planId', sa.Integer(), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['subscription_plans.planId'], ),
    sa.ForeignKeyConstraint(['roleId'], ['roles.roleId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=False)
    op.create_table('documents',
    sa.Column('documentId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filePath', sa.String(length=512), nullable=True),
    sa.Column('statusId', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['users.userId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statusId'], ['document_statuses.statusId'], ),
    sa.PrimaryKeyConstraint('documentId')
    )
    op.create_index(op.f('ix_documents_documentId'), 'documents', ['documentId'], unique=False)
    op.create_index(op.f('ix_documents_ownerId'), 'documents', ['ownerId'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_table('templates',
    sa.Column('templateId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('filePath', sa.String(length=512), nullable=False),
    sa.Column('isPublic', sa.Boolean(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['users.userId'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('templateId')
    )
    op.create_index(op.f('ix_templates_ownerId'), 'templates', ['ownerId'], unique=False)
    op.create_index(op.f('ix_templates_templateId'), 'templates', ['templateId'], unique=False)
    op.create_table('user_profiles',
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('companyName', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profileId')
    )
    op.create_index(op.f('ix_user_profiles_profileId'), 'user_profiles', ['profileId'], unique=False)
    op.create_index(op.f('ix_user_profiles_userId'), 'user_profiles', ['userId'], unique=True)
    op.create_table('workspace_members',
    sa.Column('workspaceMemberId', sa.Integer(), nullable=False),
    sa.Column('workspaceId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('roleInWorkspace', sa.String(length=50), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspaceId'], ['workspaces.workspaceId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspaceMemberId')
    )
    op.create_index(op.f('ix_workspace_members_userId'), 'workspace_members', ['userId'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspaceId'), 'workspace_members', ['workspaceId'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspaceMemberId'), 'workspace_members', ['workspaceMemberId'], unique=False)
    op.create_table('document_contents',
    sa.Column('contentId', sa.Integer(), nullable=False),
    sa.Column('documentId', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('metadataJson', sa.JSON(), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['documentId'], ['documents.documentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contentId')
    )
    op.create_index(op.f('ix_document_contents_contentId'), 'document_contents', ['contentId'], unique=False)
    op.create_index(op.f('ix_document_contents_documentId'), 'document_contents', ['documentId'], unique=True)
    op.create_table('document_conversions',
    sa.Column('conversionId', sa.Integer(), nullable=False),
    sa.Column('documentId', sa.Integer(), nullable=False),
    sa.Column('sourceFormat', sa.String(length=20), nullable=False),
    sa.Column('targetFormat', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outputFilePath', sa.String(length=512), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['documentId'], ['documents.documentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversionId')
    )
    op.create_index(op.f('ix_document_conversions_conversionId'), 'document_conversions', ['conversionId'], unique=False)
    op.create_index(op.f('ix_document_conversions_documentId'), 'document_conversions', ['documentId'], unique=False)
    op.create_table('transcriptions',
    sa.Column('transcriptionId', sa.Integer(), nullable=False),
    sa.Column('documentId', sa.Integer(), nullable=False),
    sa.Column('mediaPath', sa.String(length=512), nullable=False),
    sa.Column('mediaType', sa.String(length=50), nullable=False),
    sa.Column('durationSeconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['documentId'], ['documents.documentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transcriptionId')
    )
    op.create_index(op.f('ix_transcriptions_documentId'), 'transcriptions', ['documentId'], unique=False)
    op.create_index(op.f('ix_transcriptions_transcriptionId'), 'transcriptions', ['transcriptionId'], unique=False)
    op.create_table('translations',
    sa.Column('translationId', sa.Integer(), nullable=False),
    sa.Column('documentId', sa.Integer(), nullable=False),
    sa.Column('sourceLanguage', sa.String(length=20), nullable=False),
    sa.Column('targetLanguage', sa.String(length=20), nullable=False),
    sa.Column('mediaType', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=255), server_default='system', nullable=False),
    sa.Column('lastUpdatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedBy', sa.String(length=255), server_default='system', nullable=False),
    sa.ForeignKeyConstraint(['documentId'], ['documents.documentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('translationId')
    )
    op.create_index(op.f('ix_translations_documentId'), 'translations', ['documentId'], unique=False)
    op.create_index(op.f('ix_translations_translationId'), 'translations', ['translationId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_translationId'), table_name='translations')
    op.drop_index(op.f('ix_translations_documentId'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_transcriptions_transcriptionId'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_documentId'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_document_conversions_documentId'), table_name='document_conversions')
    op.drop_index(op.f('ix_document_conversions_conversionId'), table_name='document_conversions')
    op.drop_table('document_conversions')
    op.drop_index(op.f('ix_document_contents_documentId'), table_name='document_contents')
    op.drop_index(op.f('ix_document_contents_contentId'), table_name='document_contents')
    op.drop_table('document_contents')
    op.drop_index(op.f('ix_workspace_members_workspaceMemberId'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_workspaceId'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_userId'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_user_profiles_userId'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profileId'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_templates_templateId'), table_name='templates')
    op.drop_index(op.f('ix_templates_ownerId'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_ownerId'), table_name='documents')
    op.drop_index(op.f('ix_documents_documentId'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_workspaces_workspaceId'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_subscription_plans_planName'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_planId'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_roles_roleName'), table_name='roles')
    op.drop_index(op.f('ix_roles_roleId'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_document_statuses_statusName'), table_name='document_statuses')
    op.drop_index(op.f('ix_document_statuses_statusId'), table_name='document_statuses')
    op.drop_table('document_statuses')
    # ### end Alembic commands ###
